# Chapter 4 NumPy Basics
## The NumPy ndarray: 
### The basics:
An ndarray is a generic multidimensional container for homogeneous data; all elements must be the same type, indexed by a tuple of positive integers. In NumPy dimensions are called _axes_.
Every array has
 * __ndarray.ndim__: the number of axes (dimensions) of the array
 * __ndarray.shape__: a tuple indicating the size of each dimension. For a matrix with _n_ rows and _m_ columns, __shape__ will be _(n, m)_. The length of the __shape__ tuple is therefore the number of axes, __ndim__.
 * __ndarray.dtype__: an object describing the _data type_ of the array, NumPy provides types of its own. numpy.int32, numpy.int16, numpy.int64 are some examples.

In [11]:
import numpy as np
data = np.arange(15).reshape(3, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
data.ndim

2

In [13]:
data.shape

(3, 5)

In [15]:
data.dtype.name

'int64'

 * __ndarray.size__: the total number of elements of the array. This is equal to the product of the elements of __ndarray.shape__
 * __ndarray.itemsize__: the size in __bytes__ of each element of the array. It is equivalent to __ndarray.dtype.itemsize__.
 * __ndarray.data__: the buffer containing the actual elements of the array. Normally, we won't need to use this.

In [17]:
data.itemsize

8

In [18]:
type(data)

numpy.ndarray

### Creating ndarrays
1. The easiest way: use the __array__ function: accepts any sequence-like object and produces a new NumPy array containing the passed data. For example, a list/tuple is a good candidate for conversion:

In [4]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

Nested sequences, like a list of __equal-length__ lists, will be converted into a multidimensional array:

In [111]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

A frequent error consists in calling __array__ with multiple numeric arguments, rather than providing a single list of numbers as an argument:

In [ ]:
a = np.array(1, 2, 3, 4)    #WRONG
a = np.arrar([1, 2, 3, 4])    #RIGHT

The type of the array can also be explicitly specified at creation time:

In [20]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

2. There are a number of other functions for creating new arrays. As examples:
 * __zeros__ and __ones__ create arrays of 0s and 1s, respectively, with a given length or shape

In [22]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

 * __empty__ creates an array without initializing its values to any particular value. 

In [112]:
np.empty((2, 4, 3))    # 第三维在前
# Uninitialized, output may vary. It's not safe to assume that np.empty will return an array of all zeors,
# sometimes it will be garbages.

array([[[3.10503618e+231, 3.10503618e+231, 9.38724727e-323],
        [0.00000000e+000, 2.31297541e-312, 5.02034658e+175],
        [2.21471671e+160, 2.89830427e-057, 1.79747002e-052],
        [1.68777511e+160, 1.47763641e+248, 1.16096346e-028]],

       [[7.69165785e+218, 1.35617292e+248, 4.10985423e-061],
        [1.08672383e-071, 8.38095896e+165, 4.66450330e-033],
        [4.30422694e-096, 6.32299154e+233, 6.48224638e+170],
        [5.22411352e+257, 5.74020278e+180, 8.37174974e-144]]])

 * __arange__ analogous to __range__ that returns arrays of sequences of numbers.

In [24]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [25]:
np.arange(10, 20, 1.5)    # it accepts float arguments

array([10. , 11.5, 13. , 14.5, 16. , 17.5, 19. ])

When __arange__ is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function __linspace__ that receives as an argument the number of elements that we want, instead of the step:

In [26]:
np.linspace(0, 10, 9)    # 9 numbers from 0 to 10, both ends are inclusive

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

Array Creation Functions

Function | Description
----------- | ---------------
array | Convert input data(list, tuple, array, other sequence type) to an ndarray (explicitly specifying a dtype); copies the input data by default
asarray | Convert input to ndarray, but do not copy if the input is already an ndarray
arange | Like the built-in range but returns an ndarray instead of a list
ones | Produce an array of all 1s with the given shape and dtype 
ones_like | Produces a ones array of the same shape and dtype
zeros, zeros_like | Like ones and ones_like but producing arrays of 0s instead
empty, empty_like | Create new arrays y allocating new memory, but do not populate with any values like ones and zeros
full, full_like | Produce an array of the given shape and dtype with all values set to the indicated 'fill value'
eye, identity | Create a Square N x N identity matrix (1s on the diagonal and 0s elsewhere)

### Data Types for ndarrays
__dtype__ is a special object containing the information the ndarray needs to interpret a chunk of memory as a particular type of data, it is named in this way: a type name, like float or int, followed by a number indicating the number of bits per element:

In [34]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr2= np.array([4,5,6], dtype=np.int32)
arr1.dtype

dtype('float64')

In [36]:
arr1.dtype.itemsize

8

In [35]:
arr2.dtype

dtype('int32')

In [37]:
arr2.dtype.itemsize

4

NumPy Data Types
Type | Type Code | Description
----- | ----- | -----
int8, uint8 | i1, u1 | Signed and unsigned 8-bit integer types
int16, uint16 | i2, u2 | Signed and unsigned 16-bit ineger types
int32, uint32 | i4, u4 | Signed and unsigned 32-bit integer types
int64, uint64 | i8, u8 | Signed and unsigned 64-bit integer types
float16 | f2 | Half-precision floating point
float32 | f4 or f | Standard single-precision floating point; compatible with C float
float64 | f8 or d | Standard double-precision floating point; compatible with C double and Python float object
float128 | f16 or g | Extended-precision floating point
complex64, complex128, complex256 | c8, c16, c32 | Complex numbers represented by two 32, 64, or 128 floats, respectively
bool | ? | Boolean type storing True and False values
object | 0 | Python object type; a value can be any Python object
string_ | S | Fixed-length ASCII string type (1 byte per character); for example, to create a string dtype with length 10, use 'S10'
unicode_ | U | Fixed-length Unicode type (number of bytes platform specific); same specification semantics as string_ (e.g., 'U10')

Explicitly convert or cast an array from one dtype to another using ndarray's __astype__ method:

In [46]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [48]:
float_arr = arr.astype(np.float64)    # 使用astype时，ndarray被复制，所以不能更改原ndarray的dtype；
float_arr.dtype

dtype('float64')

If I cast some floating-point numbers to be of integer dtype, the decimal part will be truncated:

In [117]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [118]:
arr1 = arr.astype(np.int64)    # 使用astype时，ndarray被复制，所以不能更改原ndarray的dtype；
arr1.dtype

dtype('int64')

In [119]:
arr.dtype

dtype('float64')

An array of strings representing numbers, you can use __astype__ to convert them to numeric form:

In [121]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
converted_numeric_strings = numeric_strings.astype(np.float32)
converted_numeric_strings

array([ 1.25, -9.6 , 42.  ], dtype=float32)

Type Code can also be used to refer to a dtype:

In [55]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1072693248,          0, 1073741824,          0,
       1074266112,          0, 1074790400], dtype=uint32)

__Calling astype always creates a new array (a copy of the data), even if the new dtype is the same as the old dtype.__

### Arithmetic with NumPy Arrays
Arrays enable you to express batch operations on data without writing any for loops. This is called _vectorization_. Any arithmetic operations between equal-size arrays applies the operation element-wise:

In [56]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [58]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

Arithmetic operations with scalars propagate the scalar argument to each element in the array:

In [59]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [60]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

Comparisons between arrays of the same size yield boolean arrays:

In [61]:
arr2 = np.array([[0, 4, 1], [7, 2, 12]])

In [62]:
arr2

array([[ 0,  4,  1],
       [ 7,  2, 12]])

In [63]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

Operations between differently sized arrays is called __broadcasting__. 此处下面会介绍。

### Basic Indexing and Slicing
One dimensional arrays are simple; similar to Python lists:

In [65]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr[5]

5

In [67]:
arr[5:8]

array([5, 6, 7])

In [69]:
arr[5:8] = 12   #assign a scalar to a  slice
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

As we can see from the above example, if assigning a scalar value to a slice, as in arr[5:8] = 12, the value is _boradcasted_ to the entire selection. 

An important first distinction from Python's built-in lists is that array slices are _views_ on the original array. This means that the data is __not copied__, and any modifications to the view will be reflected in the source array:

In [70]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [71]:
arr_slice[1] = 12345
arr    # 修改arr_slice的值，arr跟着一块变

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

The "bare" slice [:] will assign to all values in an array:

In [72]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

If you want a copy of an ndarray instead of a view, you will need to do it explicitly using copy() method:

In [73]:
arr_copied = arr[5:8].copy()

In a two-dimensional array, the elements at each index is an one-dimensional arrays:

In [74]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d[2]

array([7, 8, 9])

Thus, individual elements can be accessed recursively. These are equivalent:

In [76]:
arr2d[0][2]

3

In [77]:
arr2d[0,2]

3

It is helpful to think of axis 0 as the "rows" of the array and axis 1 as the "columns", FOR A TWO-DIMENSIONAL NDARRAY.

In multidimensional arrays, if later indices is omitted, the returned object will be a lower dimensional ndarray consisting of all the data along the higher dimensions. So in the following 2x2x3 array arr3d:

In [83]:
arr3d = np.arange(12).reshape(2,2,3)
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

arr3d[0] is a 2x3 array:

In [84]:
arr3d[0]    # later indices omitted

array([[0, 1, 2],
       [3, 4, 5]])

Both scalar values and arrays can be assigned to arr3d[0]:

In [85]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d[0]

array([[42, 42, 42],
       [42, 42, 42]])

In [86]:
arr3d[0] = old_values
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

Similarly, arr3d[1, 0] gives you all of the values whose indices start with (1, 0), forming a 1-dimensional array:

In [87]:
arr3d[1, 0]

array([6, 7, 8])

In [88]:
arr3d[1][0] 

array([6, 7, 8])

### Indexing with slices
One-dimensional ndarrays can be sliced with the syntax similar to Python 1-d lists:

In [89]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [90]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

Slicing two-dimensional array is a bit different:

In [95]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

The selection is on the axis 0, by default:

In [96]:
arr2d[:2]  

array([[1, 2, 3],
       [4, 5, 6]])

Select multiple axis by seperate the slicing with a colon:

In [94]:
arr2d[0,:]

array([1, 2, 3])

### Boolean Indexing
Consider some data in an array called _data_, and an array of names corresponding with data _names_(the name and data at the same location in both arrays are a pair). 

In [98]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [102]:
data

array([[ 1.56392282, -0.61752948, -1.79867665,  0.82765117],
       [-0.49791997,  0.29476465,  0.87733582,  0.7985922 ],
       [ 2.0998279 ,  0.02107321, -0.52817965,  0.18371177],
       [-0.31929101, -1.04003966,  0.11207471, -1.13225772],
       [-0.58757335,  0.63610098, -1.32048101, -0.90576462],
       [-0.75543448, -1.48660288,  1.08779366, -0.59933659],
       [-0.28731428, -1.22601131, -0.18016106, -0.14642662]])

Each name corresponds to a row in the data array, if we want to select the data corresponding to a specific name, 'Bob', Like arithmetic operations, comparisons with arrays are also vectorized, comparing ndarray with a string yields a boolean array:

In [100]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

This boolean array can be passed to the _data_ array as indices:

In [101]:
data[names == 'Bob']

array([[ 1.56392282, -0.61752948, -1.79867665,  0.82765117],
       [-0.31929101, -1.04003966,  0.11207471, -1.13225772]])

__The boolean array must be of the same length as the array axis it's indexing. You can even mix and match boolean arrays with slices or integers (or sequences of integers). Boolean selection will not fail if the boolean array is NOT the correct length!!!__

We can select the rows by names and columns by integer slicing:

In [103]:
data[names == 'Bob', 2:]

array([[-1.79867665,  0.82765117],
       [ 0.11207471, -1.13225772]])

In [104]:
data[names == 'Bob', 3]

array([ 0.82765117, -1.13225772])

To select everything but 'Bob', you can either use != or negate the condition using ~:

In [106]:
data[names != 'Bob']

array([[-0.49791997,  0.29476465,  0.87733582,  0.7985922 ],
       [ 2.0998279 ,  0.02107321, -0.52817965,  0.18371177],
       [-0.58757335,  0.63610098, -1.32048101, -0.90576462],
       [-0.75543448, -1.48660288,  1.08779366, -0.59933659],
       [-0.28731428, -1.22601131, -0.18016106, -0.14642662]])

In [107]:
data[~(names == 'Bob')]

array([[-0.49791997,  0.29476465,  0.87733582,  0.7985922 ],
       [ 2.0998279 ,  0.02107321, -0.52817965,  0.18371177],
       [-0.58757335,  0.63610098, -1.32048101, -0.90576462],
       [-0.75543448, -1.48660288,  1.08779366, -0.59933659],
       [-0.28731428, -1.22601131, -0.18016106, -0.14642662]])

The ~ operator can be useful when you want to invert a general condition:

In [108]:
cond = names == 'Bob'
data[~cond]

array([[-0.49791997,  0.29476465,  0.87733582,  0.7985922 ],
       [ 2.0998279 ,  0.02107321, -0.52817965,  0.18371177],
       [-0.58757335,  0.63610098, -1.32048101, -0.90576462],
       [-0.75543448, -1.48660288,  1.08779366, -0.59933659],
       [-0.28731428, -1.22601131, -0.18016106, -0.14642662]])

Select multiple names to combine the boolean conditions, use boolean arithmetic operators &(and) and |(or):

The Python keywords _and_ and _or_ do not work with boolean arrays. Use & and | only.

In [109]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [122]:
data[mask]

array([[ 1.56392282, -0.61752948, -1.79867665,  0.82765117],
       [ 2.0998279 ,  0.02107321, -0.52817965,  0.18371177],
       [-0.31929101, -1.04003966,  0.11207471, -1.13225772],
       [-0.58757335,  0.63610098, -1.32048101, -0.90576462]])

To set all of the negative values in data to 0:

In [124]:
data[data < 0] = 0
data

array([[1.56392282, 0.        , 0.        , 0.82765117],
       [0.        , 0.29476465, 0.87733582, 0.7985922 ],
       [2.0998279 , 0.02107321, 0.        , 0.18371177],
       [0.        , 0.        , 0.11207471, 0.        ],
       [0.        , 0.63610098, 0.        , 0.        ],
       [0.        , 0.        , 1.08779366, 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

__Selecting data from an array by boolean indexing always creates a copy of the data, even if the returned array is unchanged.__

### Fancy Indexing
This is a term adopted by NumPy to describe indexing using integer arrays. Suppose we had an 8 x 4 array:

In [128]:
arr = np.empty((8,3))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.],
       [5., 5., 5.],
       [6., 6., 6.],
       [7., 7., 7.]])

To select out a subset of the rows in a particular order, you can pass a list or ndarray of integers specifying the desired order, using negative indices selects rows from the end:

In [130]:
arr[[7,5,4,6,1,3,3,-1,-1]]

array([[7., 7., 7.],
       [5., 5., 5.],
       [4., 4., 4.],
       [6., 6., 6.],
       [1., 1., 1.],
       [3., 3., 3.],
       [3., 3., 3.],
       [7., 7., 7.],
       [7., 7., 7.]])

Passing multiple index arrays is slightly different; it selects a one-dimensional array of elements corresponding to each tuple of indices:

In [132]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [133]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

Here the (1, 0), (5, 3), (7, 1), and (2, 2) elements were selected. Regardless of how many dimensions the array has, the result of fancy indexing is always one-dimensional.

### Transposing Arrays and Swapping Axes
Transposing is a special form of reshaping that returns a view without copying anything. Arrays have the _transpose_ method and also the special __T__ attribute:

In [135]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [136]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

This is useful when computing the inner matrix product using _np.dot_:

In [138]:
dot_product = np.dot(arr, arr.T)
dot_product

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

For higher dimensional arrays, __transpose__ will accept a tuple of axis numbers to permute the axes:

In [140]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [142]:
arr.transpose((1, 0, 2))   #原来的第1轴变为新的0轴，原0轴变1轴，原2轴变2轴。略抽象。

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [144]:
arr.transpose((1, 2, 0))

array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11]],

       [[ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])

Simple transposing with _.T_ is a special case of swapping axes. ndarray has the method swapaxes, which takes a pair of axis numbers and switches the indicated axes to rearange the data:

In [145]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

_swapaxes_ similarly returns a view without making a copy.

## Universal Functions: Fast Element-Wise Array Functions
a universal function, or _ufunc_, is a function that performs element-wise operations on data in ndarrays：

In [147]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [148]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [149]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

These are referred to as unary ufuncs (一元的)。 Others, such as __add__ or __maximum__, take two arrays (thus, binary ufuncs) and return a single array as the result:

In [150]:
x = np.random.randn(8)
y = np.random.randn(8)
x

array([ 1.98367672,  0.05120896, -0.57251915, -0.07261642,  2.51625868,
        0.69319505, -0.80597033,  0.25349398])

In [151]:
y

array([ 0.30958753, -0.62667397,  1.61136457,  0.66437889, -0.21171712,
       -1.49040692,  0.63417185, -0.77057024])

In [152]:
np.maximum(x, y)

array([1.98367672, 0.05120896, 1.61136457, 0.66437889, 2.51625868,
       0.69319505, 0.63417185, 0.25349398])

_np.maximum_ computed the element-wise of the elements in x and y.

While not common, a ufunc can return multiple arrays. __modf__ is one example, a vectorized version of the built-in Python __divmod__; it returns the fractional and integral parts of a floating-point array:

In [153]:
arr = np.random.randn(7) * 5
arr

array([ 5.59220577,  0.09013971, -1.04301832, -0.86250907,  3.67771433,
       -4.27465037, -0.84944355])

In [154]:
remainder, whole_part = np.modf(arr)
remainder

array([ 0.59220577,  0.09013971, -0.04301832, -0.86250907,  0.67771433,
       -0.27465037, -0.84944355])

In [155]:
whole_part

array([ 5.,  0., -1., -0.,  3., -4., -0.])

ufuncs accept an optional out argument that allows them to operate in-place on arrays (意思是可以把结果输出到指定位置？？？):

In [156]:
arr

array([ 5.59220577,  0.09013971, -1.04301832, -0.86250907,  3.67771433,
       -4.27465037, -0.84944355])

In [157]:
np.sqrt(arr)

/Users/jianbinliu/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([2.36478451, 0.30023277,        nan,        nan, 1.91773677,
              nan,        nan])

In [158]:
np.sqrt(arr, arr)

/Users/jianbinliu/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([2.36478451, 0.30023277,        nan,        nan, 1.91773677,
              nan,        nan])

In [159]:
arr

array([2.36478451, 0.30023277,        nan,        nan, 1.91773677,
              nan,        nan])

Unary ufuncs
Function | Description
-------- | ---------------------
abs, fabs | Compute the absolute value element-wise for integer, floating-point, or complex values
sqrt | Compute the square root of each element
square | Compute the square of each element
exp | Compute the exponent of each element
log, log10, log2, log1p | ln, log10, log2, log(1+x)
sign | Compute the sign of each element: 1 (>0), 0 (zero), or -1 (<0) 
ceil | Compute the ceil of each element (i.e. the smallest integer greater than or equal to that number)
floor | Compute the floor of each element (the largest integer less than or equal to each element)
rint | Round elements to the nearest integer, preserving the dtype
modf | Return fractional and integral parts of array as a separate array
isnan | Return boolean array indicating whether each value is NaN
isfinite, isinf | Return boolean array indicating whether each element is finite or infinite, repectively
cos, cosh, sin, sinh, tan, tanh | 
arccos, arccosh, arcsin, arcsinh, arctan, arctanh |
logical_not | Compute truth value of not x element-wise (equivalent to ~arr)